### ISSUE TITLE
Use of '\' as path separator breaks app on UNIX-based operating systems

### ISSUE THREAD

**Issue by jfsantos** [andrewssobral/lrslibrary#1]
The string being used to initialize text fields on `main_edit_video.fig` and `main.fig` uses the character `\` as path separator. Since this is only the path separator on Windows systems, the app demos do not work properly on OS X and Linux (and probably any UNIX-based operating system, where the path separator is `/`). A fix would be to initialize these fields from code using MATLAB's `filesep`, or maybe using `/` as the file separator (I think MATLAB accepts it as a file separator even on Windows).

**Comment by andrewssobral** [comment]
Hi @jfsantos, thank you for your remark, I'll check this.

**Comment by andrewssobral** [comment]
Hi @jfsantos, please check the last version of LRSLibrary. Best regards.
