### ISSUE TITLE
"data_2_days" dataset?

### ISSUE THREAD

**Issue by lizrehbein00** [andrewssobral/lrslibrary#10]
Hi there. I am trying to run the rpca_demo function and can't seem to locate the dataset "data_2_days" that the demo is supposed to process and analyze. Any help locating this dataset would be greatly appreciated. I'd love to be able to play around with the demo script.

Thanks!

**Comment by AgFlores** [comment]
Hi,
wich platform are you using to run ThE functión?

**Comment by lizrehbein00** [comment]
Hello,

I am just trying to run the rpca_demo function in matlab.

**Comment by andrewssobral** [comment]
Hi @lizrehbein00 ,
I did not find the rpca_demo function you are talking about, do you meant https://github.com/andrewssobral/lrslibrary/blob/master/demo.m ?

**Comment by lizrehbein00** [comment]
Hi Andrew,

I'm not looking at demo.m actually. The function I'm looking at, rpca_demo.m,  can be found under lrslibrary/algoritms/rpca/RPCA. Thanks for taking the time to try to help me!

**Comment by andrewssobral** [comment]
Hi @lizrehbein00 , here's the original source code + data:
https://gofile.io/?c=QIsyrz
in the zip file, you will find the respective `data_2_days.mat` and `pca_result_2_days.mat` files.

**Comment by lizrehbein00** [comment]
Wonderful! Thanks so much for your help.

**Comment by andrewssobral** [comment]
You're welcome
