### ISSUE TITLE
lrs_setup错误

### ISSUE THREAD

**Issue by momo-github-1984** [andrewssobral/lrslibrary#11]
>> lrs_setup
Running setup...
LRSLibrary path: C:\Users\18382\Desktop\experiment\lrslibrary-master\lrslibrary-master
Updating PATH!
Running VLFeat setup!
错误使用 run (line 46)
未找到 C:\Users\18382\Desktop\experiment\lrslibrary-master\lrslibrary-master\libs\vlfeat\toolbox\vl_setup。

出错 lrs_setup (line 61)
run(lrs_conf.vl_path); % add VLFeat

**Comment by andrewssobral** [comment]
Sorry, this is not clear for me.
