### ISSUE TITLE
Bug in RPCA | RPCA algorithm

### ISSUE THREAD

**Issue by WvanderMeer** [andrewssobral/lrslibrary#13]
When calling 'rob_pca' (line 50 in RPCA.m) the order of the Sigmaf and Sigmai parameters is wrong.
Instead of
`rob_pca(Data,number_component,300,1,Sigmaf,Sigmai,2,basis_ini,c_ini,mean_ini);`
The code should read
`rob_pca(Data,number_component,300,1,Sigmai,Sigmaf,2,basis_ini,c_ini,mean_ini);`

The final result is not much different, but the algorithm becomes a lot faster.

**Comment by andrewssobral** [comment]
Thank you @WvanderMeer for catching this issue, just fixed it on this commit https://github.com/andrewssobral/lrslibrary/commit/06d457349cb5f1fc56a583cd61af9f1d5150e3a1
