### ISSUE TITLE
data_2_days missing

### ISSUE THREAD

**Issue by milkeast** [andrewssobral/lrslibrary#15]
When I runnung the Matlab code, I can't find the file called  data_2_days.
I have searched the internet and I find a  website you give a url connection to the original source code and data file, but that url is unavailable now.(https://gofile.io/?c=QIsyrz)
Could you please help me locate the data_2_days? Any help locating this dataset would be greatly appreciated.
Thank you! Regards

**Comment by andrewssobral** [comment]
Hello @milkeast , sorry for my late reply, here's the link to the original code + data:
https://drive.google.com/drive/folders/1PR3q6UHgzVA5Mjl6L52-yFpJppPoB7Mt?usp=share_link
