### ISSUE TITLE
some problem in running lrs_gui.m

### ISSUE THREAD

**Issue by moorejee** [andrewssobral/lrslibrary#5]
Hello, I am a graduate student from China. 
There are some problems in your repository "lrslibrary". First, the library "vlfeat" is empty. Second, the file "lrs_gui.m" is also empty. Can you fix these problem soon?

**Comment by andrewssobral** [comment]
Hi @moorejee ,
You need to do: 
```git clone --recursive https://github.com/andrewssobral/lrslibrary.git```
the parameter ```--recursive``` get the submodules required for lrslibrary setup.
The [lrs_gui.m](https://github.com/andrewssobral/lrslibrary/blob/master/lrs_gui.m) is not critical, it just call the [main.m](https://github.com/andrewssobral/lrslibrary/blob/master/gui/main.m) function stored in the **gui** folder.

**Comment by moorejee** [comment]
Thanks for your answer. I run the program successfully.
